-- ONE TO ONE RELATIONSHIP

-- FIRST TABLE

CREATE TABLE STUDENTS(
STUDENT_ID SERIAL PRIMARY KEY,
NAME VARCHAR(100) NOT NULL
);

INSERT INTO STUDENTS (NAME)
VALUES
('SARVESH SINHA'),
('RAHUL'),
('ROSHAN');

SELECT * FROM STUDENTS;

-- SECOND TABLE

CREATE TABLE STUDENT_PROFILE(
STUDENT_ID SERIAL PRIMARY KEY,
ADDRESS TEXT,
AGE INT,
PHONE VARCHAR(15)
);

INSERT INTO STUDENT_PROFILE (STUDENT_ID, ADDRESS, AGE, PHONE)
VALUES
(1,'NASHIK,',21,'9999999999'),
(2,'DEHRADUN',19,'8888888888'),
(3,'DELHI',20,'7777777777');

SELECT * FROM STUDENT_PROFILE;

SELECT * FROM STUDENTS;
SELECT * FROM STUDENT_PROFILE;

-- USE FOREIGN KEY

ALTER TABLE STUDENT_PROFILE
ADD CONSTRAINT FK_STUDENT_ID
FOREIGN KEY (STUDENT_ID)
REFERENCES STUDENTS(STUDENT_ID)

-- NOW JOIN THEM USING JOIN FUNCTION

SELECT s.student_id, s.name, sp.address, sp.age, sp.phone
FROM students s
JOIN student_profile sp ON s.student_id = sp.student_id;
